FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using WebAtividadeEntrevista.Utils;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            BoBeneficiario ben = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (!ValidarCPF.EstaValido(model.CPF))
                {
                    Response.StatusCode = 400;
                    return Json(string.Join(Environment.NewLine, $"CPF Inválido"));
                }

                if (bo.VerificarExistencia(model.CPF))
                {
                    Response.StatusCode = 400;
                    return Json(string.Join(Environment.NewLine, $"CPF já cadastrado"));
                }

                model.Id = bo.Incluir(new Cliente()
                {
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF
                });

                //Adicionar Item
                if (model.Beneficiarios != null)
                {
                    foreach (var item in model.Beneficiarios)
                    {
                        ben.Incluir(new Beneficiario()
                        {
                            Nome = item.Nome,
                            CPF = item.CPF,
                            IdCliente = model.Id
                        });
                    }
                }

                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            BoBeneficiario ben = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (!ValidarCPF.EstaValido(model.CPF))
                {
                    Response.StatusCode = 400;
                    return Json(string.Join(Environment.NewLine, $"CPF Inválido"));
                }

                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF
                });

                //Itens a serem removidos
                var listaBeneficiarios = ben.ListarPorCliente(model.Id);
                foreach (var obj in listaBeneficiarios)
                {
                    if (model.Beneficiarios == null || model.Beneficiarios.FirstOrDefault(x => x.CPF == obj.CPF || x.Id == obj.Id) == null)
                    {
                        ben.Excluir(obj.Id);
                    }
                }

                //Adicionar e alterar itens
                if (model.Beneficiarios != null)
                {
                    foreach (var item in model.Beneficiarios)
                    {
                        if (item.Id == 0 && listaBeneficiarios.Count(x => x.CPF == item.CPF || x.Id == item.Id) == 0)
                        {
                            ben.Incluir(new Beneficiario()
                            {
                                Nome = item.Nome,
                                CPF = item.CPF,
                                IdCliente = item.IdCliente
                            });
                        }
                        else
                        {
                            var beneficiario = listaBeneficiarios.FirstOrDefault(x => x.CPF == item.CPF || x.Id == item.Id);
                            ben.Alterar(new Beneficiario()
                            {
                                Id = beneficiario != null ? beneficiario.Id : item.Id,
                                Nome = item.Nome,
                                CPF = item.CPF,
                                IdCliente = item.IdCliente
                            });
                        }
                    }
                }
                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id = 0)
        {
            Cliente cliente = new BoCliente().Consultar(id);
            List<BeneficiarioModel> beneficiarios = new BeneficiarioModel().Lista(new BoBeneficiario().ListarPorCliente(id));
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    CPF = cliente.CPF,
                    Beneficiarios = beneficiarios
                };
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public PartialViewResult AbrirModalBeneficiario()
        {
            return PartialView("_ModalBeneficiario");
        }
    }
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}

<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")
<div class="modal abrir-modal"></div>

@section scripts{
    <script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var listaBeneficiario = @Html.Raw(Json.Encode(Model.Beneficiarios));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/beneficiario")
    @Scripts.Render("~/bundles/carregar-modal")
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="CPF">CPF:</label>
                <input required="required" type="text" class="form-control cpf" id="CPF" name="CPF" placeholder="Ex.: 010.011.111-00">
                <b class="msg-error"></b>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                    <option value="RO">Rondônia</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div>
                <button type="button" class="btn btn-default btn-abrirModal" data-abrirmodal="@Url.Action("AbrirModalBeneficiario", "Cliente", new { })">Beneficiários</button>
            </div>
            <div class="pull-right">
                <button type="submit" class="btn btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</form>

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}

<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")
<div class="modal abrir-modal"></div>

@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var obj = null;
        var listaBeneficiario = [];
    </script>
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/beneficiario")
    @Scripts.Render("~/bundles/carregar-modal")
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
<script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';   
</script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class= "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/_ModalBeneficiario.cshtml
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Beneficiários</h4>
        </div>
        <div class="modal-body">
            <form id="formBeneficiario">
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="CPF">CPF:</label>
                            <input required="required" type="text" class="form-control cpf" id="cpf-beneficiario" name="CPF" placeholder="Ex.: 010.011.111-00">
                            <b class="msg-error"></b>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="Nome">Nome:</label>
                            <input required="required" type="text" class="form-control" id="nome-beneficiario" name="Nome" placeholder="Ex.: João" maxlength="50">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <button type="button" class="btn btn-success btn-incluir" style="margin-top: 24px;">Incluir</button>
                        </div>
                    </div>
                </div>
            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>CPF</th>
                        <th>Nome</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="tb-beneficiario">
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div>
</div>